In [1]:
import numpy as np
import time

In [2]:
a = np.zeros(4)
print(f"np.zeros(4) : a = {a}, a shape = {a.shape} a datatype = {a.dtype}")

a = np.zeros((4, 5))
print(f"np.zeros(4) : a = {a}, a shape = {a.shape} a datatype = {a.dtype}")

a = np.random.random_sample(4)
print(f"np.random.random_samples(4) : a = {a}, a shape = {a.shape} a datatype = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,) a datatype = float64
np.zeros(4) : a = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], a shape = (4, 5) a datatype = float64
np.random.random_samples(4) : a = [0.23334559 0.11642206 0.1656118  0.68004178], a shape = (4,) a datatype = float64


## Operations on Vectors 

In [3]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


## Slicing 

### Slicing creates an array of indices using a set of three values (start:stop:step). A subset of values is also valid. Its use is best explained by example:  

In [4]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


## Single Vector Operations

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
print(f"a : {a}")

b = -a
print(f"b : {b}")

b = np.sum(a)
print(f"Sum of all values of a : {b}")

b = np.mean(a)
print(f"Mean of a : {b}")

b = a**2
print(f"Squared a : {b}")

a : [1 2 3 4 5 6]
b : [-1 -2 -3 -4 -5 -6]
Sum of all values of a : 21
Mean of a : 3.5
Squared a : [ 1  4  9 16 25 36]


## Vector Vector Element Wise Operations

In [10]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [11]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print(f"Error Message : {e}")

Error Message : operands could not be broadcast together with shapes (4,) (2,) 


## Scalar Vector Operations 

In [12]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


## Vector Vector Dot Product  

In [29]:
np.random.seed(1)    #SAME RANDOM VALUE EVERY TIME

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()        #start time
c = np.dot(a, b)
toc = time.time()        #end time

print(f"np.dot(a, b) : {c}")
print(f"Start time : {tic}")
print(f"End time : {toc}")
print(f"Total Execution Time : {1000*(toc - tic):.4f} ms")

del(a);del(b)           #removes the array from memory

np.dot(a, b) : 2501072.581681313
Start time : 1790936157.1001263
End time : 1790936157.1068113
Total Execution Time : 6.6850 ms


## Vector Vector Operations 

In [32]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"[X] has shape : {X.shape}")
print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")     #No longer a matrix, just a value, thats why no shape

[X] has shape : (4, 1)
X[1] has shape (1,)
w has shape (1,)
c has shape ()


## Matrices 

## Matrix Creation 

In [39]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]


## Operations on Matrices 

## Indexing 

In [48]:
a = np.arange(6).reshape(-1, 2)      #-1 -> NumPy figures out the dimension 
                                    #for row
print(f"Shape of Matrix a : {a.shape}")
print(a)

#access an element
print(f"a[2, 0] = {a[2, 0]}")

#access a row
print(f"a[2] = {a[2]}")

Shape of Matrix a : (3, 2)
[[0 1]
 [2 3]
 [4 5]]
a[2, 0] = 4
a[2] = [4 5]


## Slicing

In [58]:
a = np.arange(20).reshape(-1, 10)
print("Original Matrix : ")
print(a)
print("\n\n")

#access 5 consecutive elements (start:stop:step)
b = a[0, 2:7:1]
print(b)
print(b.shape)

#access all elements
b = a[:,:]
print(b)
print(b.shape)

#access all elements in 1 row
b = a[0,:]
print(b)
print(b.shape)

Original Matrix : 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]



[2 3 4 5 6]
(5,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
[0 1 2 3 4 5 6 7 8 9]
(10,)
